### PR TITLE
Rename filenames of source and builds to "Family-Style"

### PR DESCRIPTION
**Pull request by madig**
Fontbakery requires filenames to match this style.

### CODE REVIEW

**Comment by madig** [comment]
(The diff is a bit of a massacre because git lists each rename)

**Comment by sladen** [comment]
Suspect this can be archived with a smaller diff by adding a dozen lines to the Makefile to copy each to the FontBakery happiness name.

**Comment by madig** [comment]
Ok, leaving this for later.

**Comment by sladen** [comment]
Different solution to this for the moment … `make release` will populate a directory of appropriately named TTFs, suitable for then running Fontbakery over, or building a Zip/Tarball archive from.

**Pull request closed without merging**
