### PR TITLE
Update requirements.txt to look for the latest upstream release

### PR DESCRIPTION
**Pull request by madig**
It was looking for specific commits and a custom fontmake branch before.
The previously required fontmake pull request has since been included.

### CODE REVIEW

**Comment by madig** [comment]
Not sure if it makes sense to pin versions here?

**Comment by sladen** [comment]
Everything should be upstream now so it should "just work".

If version is needed, probably only the minimum versions/commit-id with that fix/feature.

(And if something does break, we can still recover the revision from the Git history, so quite happy to merge this.

**Comment by anthrotype** [comment]
if you don't pin the version, the built output will not be deterministic. You should expect to get different fonts if you re-run a build at a later time, depending on what happens to be the latest available version on PyPI.

**Comment by madig** [comment]
Right. Also pin sub-requirements by other packages?

**Comment by anthrotype** [comment]
That’s not a bad idea. It just can get tiresome to keep up to date (that’s why services like pyup.io exist)

**Comment by madig** [comment]
Okay. Squash the commits?

**Comment by anthrotype** [comment]
What I would do (it can be done in a separate PR) is a Makefile target called, say, "update-requirements" that creates a temporary virtual environment, pip installs the top-level requirements only without specific versions (i.e. the latest as none is installed in the new venv), then calls `pip freeze > requirements.txt` to overwrite the contents of the current requirements.txt file. You can manually run that command from time to time and commit the result, to make sure you're running the latest packages.

**Comment by madig** [comment]
I have squashed and rebased the commit to keep history clean.

The Makefile updater sounds like a good idea, will have a look.

**Comment by anthrotype** [comment]
technically speaking, the only top-level requirement (which is not a dependency of something else) here is fontmake, all the others are dependencies of fontmake.

**Comment by madig** [comment]
Okay, that and vttLib if I see correctly.

**Comment by anthrotype** [comment]
yes. when in doubt, check `install_requires` in setup.py. That's the ultimate source of truth for pip to resolve dependencies.

**Comment by madig** [comment]
Hm. No setup.py here, maybe it becomes necessary when we'll introduce (unit) tests and things?

**Comment by anthrotype** [comment]
setup.py is only for python modules that are built via distutils/setuptools and installed with pip.
this is a font source repository that uses python packages to build. It has requirements.txt, but not setup.py.

unless you want to `pip install ubuntu` :)

**Comment by anthrotype** [comment]
Sorry if I confused you. I meant, check the setup.py of the modules you wish to install to figure out the list of dependencies. Actually, that metadata field should also be reflected on the PyPI page (e.g. https://pypi.python.org/pypi/fontmake), under "Requires Distributions"

**Comment by moyogo** [comment]
Thanks!

**Pull request merged**
